### ISSUE TITLE
Jade file is overwritten when built

### ISSUE THREAD

**Issue by nikarc** [negibouze/html-webpack-pug-plugin#12]
My source file is `index.jade`:
```
doctype html
html
  head
    meta(charset='utf-8')
    meta(name='viewport', content='width=device-width, initial-scale=1')
    title ots-box-office
  body
    #app
    // built files will be auto injected
    script(src='https://js.stripe.com/v3/')
    script.
      window.__API__ = !{self.htmlWebpackPlugin.options ? self.htmlWebpackPlugin.options.__API__ : __API__};
      window.__STRIPE_API_KEY__ = !{self.htmlWebpackPlugin.options ? self.htmlWebpackPlugin.options.__STRIPE_API_KEY__ : __STRIPE_API_KEY__};
      window.__OTS_URL__ = !{self.htmlWebpackPlugin.options ? self.htmlWebpackPlugin.options.__OTS_URL__ : __OTS_URL__};
      window.__EVENT__ = !{self.htmlWebpackPlugin.options ? self.htmlWebpackPlugin.options.__EVENT__ : __EVENT__};
```

When I run `npm run build`, the Stripe script tag, and my script block with template variables is not outputted to the `/dist/index.jade` file:

```doctype html
html
  head
    meta(charset="UTF-8")
    title Webpack App
    link(href="/static/css/app.5e32a0410956d57462982963941fe2b2.css" rel="stylesheet")
  body
    script(type="text/javascript" src="/static/js/manifest.1faf18cc3c81a9eb4c42.js")
    script(type="text/javascript" src="/static/js/vendor.5a7e0d3d6d5dcaa3523a.js")
    script(type="text/javascript" src="/static/js/app.9b827a1bbdf30c5ff63a.js")
```

How can I keep the script tags when I do `npm run build`?

**Comment by negibouze** [comment]
Thank you for your report.
I will check it.

**Comment by negibouze** [comment]
@nikarc 
I tried, but could not reproduce.
Since I added an example, please confirm.
[examples/jade](https://github.com/negibouze/html-webpack-pug-plugin/tree/master/examples/jade)

**Comment by nikarc** [comment]
@negibouze,

Thanks for taking the time to make that example! I'm not sure i understand what the `index-tab.jade` file is. Can you explain that? Either way, i created `index-tab.jade` and i copied/pasted from your `webpack.config.js` from the example the following lines:

```
new HtmlWebpackPlugin({
      template: 'index.jade',
      filename: 'output.jade'
    }),
    new HtmlWebpackPlugin({
      template: 'index-tab.jade',
      filename: 'output-tab.jade'
    }),
new HtmlWebpackPugPlugin()
```

But in my `output.jade` file, im almost getting the desired output, except its in html and the jade variables are blank:

```
<!DOCTYPE html><html><body><div id="app"></div><!-- built files will be auto injected--><script>window.__API__ = ;
window.__STRIPE_API_KEY__ = ;
window.__OTS_URL__ = ;
window.__EVENT__ = ;</script><script type="text/javascript" src="/static/js/manifest.2994b6fb44e1389caf82.js"></script><script type="text/javascript" src="/static/js/vendor.353e7971b4eb1fa222b0.js"></script><script type="text/javascript" src="/static/js/app.a35ad0bce3b800d883c5.js"></script></body></html>
```

**Comment by negibouze** [comment]
@nikarc 
Thank you for your response.

`index.jade`: Indentation is space.
`index-tab.jade`: Indentation is tab.
Since there was something that did not work well with tabs before, I am checking.

Your output has been converted to HTML.
Perhaps, are you using something loader (e.g. pug-loader)?
If you are using, please refer to https://github.com/negibouze/html-webpack-pug-plugin/issues/6 .

**Comment by nikarc** [comment]
@negibouze,

That did it!! After removing the `pug-loader` from `webpack-config`, its working correctly. Thank you!
