### ISSUE TITLE
Used with webpack-dev-middleware

### ISSUE THREAD

**Issue by PlayMa256** [negibouze/html-webpack-pug-plugin#17]
Hello, i'm trying to use this in conjunction with dev-middleware + express. To be able to render i have a route where it just returns the output of webpack. With a normal html file i'm able to do this but i could not find the best options to read from the memory and be able to render, and also pass values to be embedded into the pug template...

Do you have any ideas?

**Comment by negibouze** [comment]
@PlayMa256 
Sorry for my late reply.
I'm sorry, but for now, I do not have a good idea.
I'll also try to find a solution.
