### ISSUE TITLE
Line after head is not indented

### ISSUE THREAD

**Issue by jeremytowne** [negibouze/html-webpack-pug-plugin#20]
The line after the `head` seems to not be indented properly. The rest of the file seems to be indented properly, but the line after `head` is not indented at all.

Ex:
template.pug:
```
doctype html
html(lang='en')
  head
    title
      block pageTitle
```
output:
```
doctype html
html(lang='en')
  head
title
      block pageTitle
```

**Comment by negibouze** [comment]
@jeremytowne 
Thank you for your report.

**Comment by negibouze** [comment]
@jeremytowne 
It is a temporary workaround.
Try putting meta above title.
like this:
```
doctype html
html(lang='en')
  head
    meta(charset="utf-8")
    title
      block pageTitle
  body
```

**Comment by jeremytowne** [comment]
@negibouze thank you for the quick response! I think the fix is to change the regex to:
`var regExp = /^(([ |\t]*)html.*\n)(([ |\t]*)head\n)([ |\t]*[\s\S]*)(\n[ |\t]*body)/im;`

**Comment by jeremytowne** [comment]
Also, it seems like your workaround is working for me in the meantime.

**Comment by negibouze** [comment]
@jeremytowne 
I released a new version(v1.0.1).
Thank you for your cooperation :)

**Comment by jeremytowne** [comment]
Thank you @negibouze!

**Comment by jeremytowne** [comment]
1.0.1 is working without the `meta` workaround, closing :)
