### ISSUE TITLE
Breaks if there's word "body" anywhere in the content (not tag)

### ISSUE THREAD

**Issue by szimek** [negibouze/html-webpack-pug-plugin#7]
This plugin won't work correctly if there's any "body*" word in the content of the pug file. 

E.g. in such case:
```pug
doctype html
html
  head
    meta(charset="utf-8")
    title Bodyweight training
  body
    #root
```

it will generate:
```pug
doctype html
html
  head
    meta(charset="utf-8")
    title  link(href="css/app-f3c2fb29e007744ea4a5.css" rel="stylesheet")
 Bodyweight training
  body
    #root
  script(type="text/javascript" src="js/app-f3c2fb29e007744ea4a5.bundle.js")
```

It can be fixed by changing the regexp used from `/( *)(%?body)/i` to `/^( *)(%?body)\b/im` (in line [#138](https://github.com/negibouze/html-webpack-pug-plugin/blob/master/index.js#L138)).

I can prepare PR for it, but because there are no tests, I'm not sure if it won't break anything.

BTW. It might be a better idea to parse PUG using their parser to get AST and modify that instead using regexes, but then it would support only PUG files...

**Comment by negibouze** [comment]
Thank you for your report and PR.
And I'm sorry for the late reply.

I will append examples and release new version.

> It might be a better idea to parse PUG using their parser to get AST and modify that instead using regexes, but then it would support only PUG files...

Thank you for your idea too.

**Comment by negibouze** [comment]
I released a new version.
